[[plugins]]
repo = 'w0rp/ale'
on_ft = ['javascript']
hook_add = '''
  let g:ale_sign_error = 'P>'
  let g:ale_sign_warning = 'P-'
  let g:ale_echo_msg_format = '[%linter%] %code: %%s'
  let g:ale_statusline_format = ['E%d', 'W%d', 'OK']

  nmap <silent> <C-w>j <Plug>(ale_next_wrap)
  nmap <silent> <C-w>k <Plug>(ale_previous_wrap)

  let g:ale_fixers = {
  \   'typescript': ['prettier'],
  \   'typescriptreact': ['prettier'],
  \   'javascript': ['prettier'],
  \   'javascriptreact': ['prettier'],
  \   'css': ['prettier'],
  \   'eruby': ['prettier'],
  \}

  " ファイル保存時に実行
  let g:ale_fix_on_save = 1

  " ローカルの設定ファイルを考慮する
  let g:ale_javascript_prettier_use_local_config = 1
  let g:ale_javascript_prettier_options = '--single-quote --trailing-comma all'
'''

# [[plugins]]
# repo = 'prettier/vim-prettier'
# build = 'npm install'

[[plugins]]
repo = 'sbdchd/neoformat'
hook_add = '''
let g:neoformat_javascript_prettiereslint = {
  \ 'exe': './node_modules/.bin/prettier-eslint',
  \ 'args': ['--stdin'],
  \ 'stdin': 1,
  \ }
let g:neoformat_typescript_prettiertslint = {
  \ 'exe': './node_modules/.bin/prettier-eslint',
  \ 'args': ['--stdin'],
  \ 'stdin': 1,
  \ }
augroup fmt
  autocmd!
  autocmd BufWritePre * Neoformat
augroup END
let g:neoformat_enabled_javascript = ['prettiereslint']
let g:neoformat_enabled_typescript = ['prettiertslint']
'''

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']
hook_add = '''
  let g:jsx_ext_required = 0
'''

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript']

[[plugins]]
repo = 'othree/es.next.syntax.vim'
on_ft = ['javascript']

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
on_ft = ['javascript']
hook_add = '''
  let g:use_javascript_libs = 'jquery,underscore,react,flux,jasmine,chai'
  let b:javascript_lib_use_jquery = 1
  let b:javascript_lib_use_underscore = 1
  let b:javascript_lib_use_react = 1
  let b:javascript_lib_use_flux = 1
  let b:javascript_lib_use_jasmine = 1
  let b:javascript_lib_use_chai = 1
'''

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['javascript']

# [[plugins]]
# repo = 'neoclide/vim-jsx-improve'
# on_ft = ['javascript']
# 
[[plugins]]
repo = 'rschmukler/pangloss-vim-indent'
on_ft = ['javascript']

# [[plugins]]
# repo = 'leafgarland/typescript-vim'
# on_ft = ['typescript']
# 
# [[plugins]]
# repo = 'clausreinke/typescript-tools.vim'
# on_ft = ['typescript']
# build = 'npm install'
# 
# [[plugins]]
# repo = 'burner/vim-svelte'
# on_ft = ['svelte']

