# [[plugins]]
# repo = 'tpope/vim-endwise'
# on_ft = ['ruby']
# 
# [[plugins]]
# repo = 'Shougo/deoplete-rct'
# on_ft = ['ruby']
# 
# [[plugins]]
# repo = 'fishbullet/deoplete-ruby'
# on_ft = ['ruby']
# 
# [[plugins]]
# repo = 'osyo-manga/vim-monster'
# on_i = 1
# on_ft = ['ruby']
# hook_add = '''
# let g:monster#completion#rcodetools#backend = "async_rct_complete"
# let g:deoplete#sources#omni#input_patterns = {
#   \ "ruby" : '[^. *\t]\.\w*\|\h\w*::',
#   \}
# '''
# 
# [[plugins]]
# repo = '5t111111/denite-rails'
# on_ft = ['ruby']
# hook_add = '''
#   nnoremap [urails] <Nop>
#   nmap     <Space>r [urails]
# 
#   nnoremap [urails]r :Denite<Space>rails:
#   nnoremap <silent> [urails]m :<C-u>Denite<Space>rails:model<CR>
#   nnoremap <silent> [urails]c :<C-u>Denite<Space>rails:controller<CR>
#   nnoremap <silent> [urails]v :<C-u>Denite<Space>rails:view<CR>
# '''
# 

